[versions]
agp = "8.10.1"
bcpkix-jdk18on = "1.79"
kotlin = "2.1.20"
ktoml = "0.7.0"
annotation = "1.9.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix-jdk18on" }
cxx = { module = "org.lsposed.libcxx:libcxx", version = "27.0.12077973" }
ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
ktoml-file = { module = "com.akuleshov7:ktoml-file", version.ref = "ktoml" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
lsplugin-cmaker = { id = "org.lsposed.lsplugin.cmaker", version = "1.2" }
